### ISSUE TITLE
[Feature Request] Argument missing handling

### ISSUE THREAD

**Issue by charlie-moomoo** [AWeirdScratcher/linelib#2]
Currently, if the command is missing an argument, it will occur following error:
```py
Exception on /webhook [POST]
Traceback (most recent call last):
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/linelib/http/portal.py", line 126, in webhook_handler
    self._go_over_cmds(e)
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/linelib/http/portal.py", line 138, in _go_over_cmds
    i(e)
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/linelib/http/portal.py", line 374, in TextEmitter
    raise err
  File "/home/runner/LineBot/venv/lib/python3.10/site-packages/linelib/http/portal.py", line 367, in TextEmitter
    if transform[_t](_all[i]) != "":
IndexError: string index out of range
```
We should be able to handle the error, so we can warn the user give all arguments.

**Comment by AWeirdScratcher** [comment]
How about more exception handlers?
Such as command not found, error while processing commands / events… etc.

**Comment by charlie-moomoo** [comment]
I wish I could do something like this:
```py
def error():
  print('oh no')

class MyCog(Client.Commands, prefix="!"):
  @cmd(name="hi",on_error=error)
  def hi(ctx):
    ctx.reply('hi')
```

**Comment by AWeirdScratcher** [comment]
Generally, if there are too many errors to handle, it might cause you to create too many functions OUTSIDE the cog.
I think using an event handler would be the best:
```py
class Cog(Client.Commands, ...):
  @cmd(name=...)
  def fn(ctx):
    ...

  @fn.error()
  def on_error(ctx, error):
    ctx.reply(
        "I know you hate errors" if isinstance(error, BadArguments) else "ok idk what error"
    )
```

**Comment by charlie-moomoo** [comment]
Oh, that looks good. :)

**Comment by sus2790** [comment]
And rename `cmd` to `command` please,.

**Comment by AWeirdScratcher** [comment]
Hey, @charlie-moomoo.
Thanks for the advice, I've added it to Linelib, you can now access it with the following script:
```py
cmd = Client.Commands.cmd
class foo(Client.Commands):
    @cmd(...)
    def bar(ctx, arg1: str):
        pass
    @bar.error()
    def onError(ctx, error):
        ctx.reply("Please pass in arguments properly.")
```

Additionally, I'd like to provide you more detailed info about the triggering.

The `@bar.error()` script will be triggered when the following occurrs:
- Missing Parameters (arguments)
- Cannot transfer `str` to the *requested type*

> *requested type: You can assign them inside your functions: `func(ctx, foo: str, bar:  int)` linelib will auto-convert them into specified types.*

However, the `Client.command` method will remain **unchanged** until further notice.

Cheers!
AWeirdDev

**Comment by AWeirdScratcher** [comment]
> @sus2790: And rename `cmd` to `command` please,.

Hey there!
As @charlie-moomoo referenced in their issue, the `cmd` **variable** is pointed directly to **`Client.Commands.cmd` (an alias of `Client.Commands.command`**.

If you want to create a basic command, use the following instead:
```py
@client.command
```

Thanks!
